### ISSUE TITLE
Prefix to prf - Injex.js

### ISSUE THREAD

**Issue by riforik** [riforik/Rikard-Discord-Bot#3]
## Prefix to prf
Prefix is undefined for [possible reasons](#notes).

#### Notes
> Potential Fixes:
> 1. Prefix variable must go to prf **(the fix)**

#### Error
```shell
(node:4648) UnhandledPromiseRejectionWarning: ReferenceError: prf is not defined
    at Client.bot.on (C:\Users\Isaiah Robinson\Documents\Riforik\Twitch\RikardDiscordBot\index.js:221
:48)
    at Client.emit (events.js:198:13)
    at MessageCreateHandler.handle (C:\Users\Isaiah Robinson\Documents\Riforik\Twitch\RikardDiscordBo
t\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Isaiah Robinson\Documents\Riforik\Twitch\RikardDiscord
Bot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65 at WebSocketConnection.onPacket (C:\Users\Isaiah Robinson\Documents\Riforik\Twitch\RikardDiscordB
ot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Isaiah Robinson\Documents\Riforik\Twitch\RikardDiscord
Bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Isaiah Robinson\Documents\Riforik\Twitch\RikardDiscordBot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver._receiver.onmessage (C:\Users\Isaiah Robinson\Documents\Riforik\Twitch\RikardDiscordBot\node_modules\ws\lib\websocket.js:137:47)
    at Receiver.dataMessage (C:\Users\Isaiah Robinson\Documents\Riforik\Twitch\RikardDiscordBot\node_modules\ws\lib\receiver.js:409:14)
(node:4648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch
(). (rejection id: 1)
(node:4648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by riforik** [comment]
Fixed
